---

- name: Installing dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - postgresql
    - postgresql-contrib
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Creating directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/jupyter/spark/jars

- name: Installing Postgresql JAR
  get_url:
    url: https://jdbc.postgresql.org/download/postgresql-{{POSTGRESQL_VERSION}}.jar
    dest: /opt/jupyter/spark/jars/

- name: Adding Notebooks | Demos
  copy:
    src: notebooks/demos
    dest: "{{ JUPYTER_DIR }}/notebooks/demos"
    owner: "{{ JUPYTER_USER }}"

- name: Adding Notebooks | tutorials
  copy:
    src: notebooks/tutorials
    dest: "{{ JUPYTER_DIR }}/notebooks/tutorials"
    owner: "{{ JUPYTER_USER }}"

- name: Adding Notebooks | sigma
  copy:
    src: notebooks/sigma
    dest: "{{ JUPYTER_DIR }}/notebooks/sigma"
    owner: "{{ JUPYTER_USER }}"

- name: Copy spark configuration
  copy:
    src: spark/
    dest: "{{ SPARK_HOME }}/conf/"
    owner: "{{ JUPYTER_USER }}"

- name: Copy scripts
  copy:
    src: scripts/
    dest: "{{ JUPYTER_DIR }}/scripts/"
    owner: "{{ JUPYTER_USER }}"
